version: '3.1'  # if no version is specified then v1 is assumed. Recommend v2 minimum

services:  # containers. same as docker run
  tomcat: # a friendly name. this is also DNS name inside network
    build: .
    ports:
      - '8080:8080'
      - '8000:8000'
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
    volumes:
      - ./build/libs/:/usr/local/tomcat/webapps
    
